# Generated by Django 5.1.3 on 2025-02-16 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='artistTbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='')),
                ('email', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('place', models.CharField(max_length=100)),
                ('pin', models.BigIntegerField()),
                ('post', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='bookingsTbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='chatTbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('message', models.CharField(max_length=599)),
            ],
        ),
        migrations.CreateModel(
            name='loginTbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='designTbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='')),
                ('description', models.CharField(max_length=599)),
                ('status', models.CharField(default='available', max_length=100)),
                ('ARTIST', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MYAPP.artisttbl')),
            ],
        ),
        migrations.AddField(
            model_name='artisttbl',
            name='LOGINID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MYAPP.logintbl'),
        ),
        migrations.CreateModel(
            name='paymentsTbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('BOOKINGID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MYAPP.bookingstbl')),
            ],
        ),
        migrations.CreateModel(
            name='postTbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=400)),
                ('design', models.FileField(upload_to='')),
                ('date', models.DateField()),
                ('postname', models.CharField(max_length=100)),
                ('ARTIST', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MYAPP.artisttbl')),
            ],
        ),
        migrations.CreateModel(
            name='productTbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('work', models.FileField(upload_to='')),
                ('description', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('ARTIST', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MYAPP.artisttbl')),
            ],
        ),
        migrations.CreateModel(
            name='schedulesTbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('ARTIST', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MYAPP.artisttbl')),
            ],
        ),
        migrations.AddField(
            model_name='bookingstbl',
            name='SCHEDULE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MYAPP.schedulestbl'),
        ),
        migrations.CreateModel(
            name='userTbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('place', models.CharField(max_length=100)),
                ('pin', models.BigIntegerField()),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MYAPP.logintbl')),
            ],
        ),
        migrations.CreateModel(
            name='reviewTbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
                ('date', models.DateField()),
                ('USERID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MYAPP.usertbl')),
            ],
        ),
        migrations.CreateModel(
            name='likeTbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('like', models.IntegerField()),
                ('POSTID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MYAPP.posttbl')),
                ('USERID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MYAPP.usertbl')),
            ],
        ),
        migrations.CreateModel(
            name='complaintsTbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=750)),
                ('reply', models.CharField(max_length=599)),
                ('date', models.DateField()),
                ('USERID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MYAPP.usertbl')),
            ],
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('POSTID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MYAPP.posttbl')),
                ('USERID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MYAPP.usertbl')),
            ],
        ),
        migrations.AddField(
            model_name='bookingstbl',
            name='USERID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MYAPP.usertbl'),
        ),
    ]
