# Generated by Django 5.1.3 on 2025-02-16 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MYAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='artistreviewTbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
                ('date', models.DateField()),
                ('ARTIST', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MYAPP.artisttbl')),
                ('USERID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MYAPP.usertbl')),
            ],
        ),
    ]
