# Generated by Django 5.1.3 on 2025-02-23 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MYAPP', '0002_artistreviewtbl'),
    ]

    operations = [
        migrations.AddField(
            model_name='chattbl',
            name='from_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='s', to='MYAPP.logintbl'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chattbl',
            name='to_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='v', to='MYAPP.logintbl'),
            preserve_default=False,
        ),
    ]
