# Generated by Django 5.1.3 on 2025-02-26 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MYAPP', '0003_chattbl_from_id_chattbl_to_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderTbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('status', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('qty', models.IntegerField()),
                ('USERID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MYAPP.usertbl')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MYAPP.producttbl')),
            ],
        ),
    ]
