# Generated by Django 5.1.3 on 2025-02-26 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MYAPP', '0004_ordertbl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentstbl',
            name='BOOKINGID',
        ),
        migrations.AddField(
            model_name='paymentstbl',
            name='ORDER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MYAPP.ordertbl'),
            preserve_default=False,
        ),
    ]
