# Generated by Django 5.1.3 on 2025-02-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MYAPP', '0005_remove_paymentstbl_bookingid_paymentstbl_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttbl',
            name='amount',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
