# Generated by Django 5.1.3 on 2025-03-01 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MYAPP', '0006_producttbl_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductpaymentsTbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('PRODUCT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MYAPP.producttbl')),
            ],
        ),
    ]
