# Generated by Django 5.1.3 on 2026-02-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MYAPP', '0007_productpaymentstbl'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingstbl',
            name='payment_status',
            field=models.CharField(default='unpaid', max_length=100),
        ),
    ]
